#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'celery==3.1.9','console_scripts','celery'
__requires__ = 'celery==3.1.9'
import sys
import os
from pkg_resources import load_entry_point
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
PROJECT_ROOT = PROJECT_ROOT.replace('/masterinterface','')
sys.path.append(PROJECT_ROOT)

if __name__ == '__main__':
    sys.exit(
        load_entry_point('celery==3.1.9', 'console_scripts', 'celery')()
    )
